[tool.poetry]
name = "pynecone-io"
version = "0.1.7"
description = "The easiest way to build web apps."
license = "Apache-2.0"
authors = [
    "Nikhil Rao <nikhil@pynecone.io>",
    "Alek Petuskey <alek@pynecone.io>",
]
readme = "README.md"
homepage = "https://pynecone.io"
repository = "https://github.com/pynecone-io/pynecone"
documentation = "https://pynecone.io/docs/getting-started/introduction"
keywords = [
    "web",
    "framework",
]
classifiers = [
    "Development Status :: 4 - Beta",
]
packages = [
    {include = "pynecone"}
]

[tool.poetry.dependencies]
python = "^3.7.2"
fastapi = "^0.88.0"
gunicorn = "^20.1.0"
plotly = "^5.10.0"
pydantic = "1.10.2"
requests = "^2.28.1"
sqlmodel = "^0.0.8"
typer = "0.4.2"
uvicorn = "^0.20.0"
rich = "^12.6.0"
redis = "^4.3.5"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pyright = "^1.1.229"
darglint = "^1.8.1"
pydocstyle = "^6.1.1"
toml = "^0.10.2"
isort = "^5.10.1"
pylint = "^2.14.5"
pytest-asyncio = "^0.20.1"
black = "^22.10.0"

[tool.poetry.scripts]
pc = "pynecone.pc:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
