[tool.poetry]
name = "pynecone"
version = "0.1.16"
description = "Web apps in pure Python."
license = "Apache-2.0"
authors = [
    "Nikhil Rao <nikhil@pynecone.io>",
    "Alek Petuskey <alek@pynecone.io>",
]
readme = "README.md"
homepage = "https://pynecone.io"
repository = "https://github.com/pynecone-io/pynecone"
documentation = "https://pynecone.io/docs/getting-started/introduction"
keywords = [
    "web",
    "framework",
]
classifiers = [
    "Development Status :: 4 - Beta",
]
packages = [
    {include = "pynecone"}
]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.88.0"
gunicorn = "^20.1.0"
plotly = "^5.10.0"
pydantic = "1.10.2"
sqlmodel = "^0.0.8"
typer = "0.4.2"
uvicorn = "^0.20.0"
rich = "^12.6.0"
redis = "^4.3.5"
httpx = "^0.23.1"
python-socketio = "^5.7.2"
psutil = "^5.9.4"
websockets = "^10.4"
cloudpickle = "^2.2.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-mock = "^3.10.0"
pyright = "^1.1.229"
darglint = "^1.8.1"
toml = "^0.10.2"
pytest-asyncio = "^0.20.1"
black = "^22.10.0"
ruff = "^0.0.244"

[tool.poetry.scripts]
pc = "pynecone.pc:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]

[tool.ruff]

select = ["B", "D", "E", "F", "I", "SIM", "W"]

ignore = ["B008", "D203", "D205", "D213", "D401", "D406", "D407", "E501", "F403", "F405", "F541"]

target-version = "py37"

[tool.ruff.per-file-ignores]

"__init__.py" = ["F401"]
"tests/*.py" = ["D100", "D103", "D104"]
"pynecone/.templates/*.py" = ["D100", "D103", "D104"]